#!/usr/bin/python
import xlrd
import csv
from glob2 import glob
from os import path
import sys

def csv_from_excel(src, dest):
	wb = xlrd.open_workbook(src)
	sh = wb.sheet_by_name('Sheet1')
	csv_file = open(dest, 'wb')
	wr = csv.writer(csv_file, quoting=csv.QUOTE_NONE)
	for rownum in xrange(sh.nrows):
	    wr.writerow(sh.row_values(rownum))
	csv_file.close()


# extract globs
if len(sys.argv) == 0:
	sys.exit(0)

for src in sys.argv[1:]:
	files = glob(src)
	for file in files:
		directory = path.dirname(file)
		fname, ext = path.splitext(file)
		if ext.startswith('.xls'):
			csv_from_excel(file, fname+'.csv')


